<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Reflow.Infrastructure\Reflow.Infrastructure.csproj" />
    <ProjectReference Include="..\Reflow.Modules.DataProcessing\Reflow.Modules.DataProcessing.csproj" />
  </ItemGroup>

</Project>
